# Site settings
title: Adam Procter, Ph.D.
email: amp269@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 So I figured I would move my website to GitHub Pages.
baseurl: ""
url: "http://test.adamprocter.com" # the base hostname & protocol for your site
github_username:  aprocter

# Build settings
markdown: kramdown

collections:
  publications:
    output: true
